### ISSUE TITLE
upgrade devpi-server to support pip search

### ISSUE THREAD

**Issue by jackiect** [scrapinghub/docker-devpi#11]
After running a docker-devpi container, I follow devpi [latest guide](http://doc.devpi.net/latest/quickstart-pypimirror.html#using-pip-search), use command `pip search --index http://localhost:3141/root/pypi/ devpi-client` to search, than I get an HTTP error

```
HTTP error 404 while getting http://localhost:3141/root/pypi/
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1091, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1431, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 786, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 404 Client Error: cannot submit to pypi mirror
```

and then I check the devpi version

```
root@e82553c6a336:~# devpi-server --version
2.5.3
root@e82553c6a336:~# devpi --version       
2.3.2
```

**Comment by lieryan** [comment]
The current devpi-server installed by docker-devpi also cannot install packages with dots in its name due to https://github.com/pypa/pip/issues/3666
